#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ ! -z "${LGTM_SRC:-}" ]]; then
  cd "${LGTM_SRC}"
fi

git clone https://github.com/UIUC-PPL/charm.git

pushd charm

./build charm++ netlrts-linux-x86_64 smp -g3 -2 --with-production --enable-error-checking

popd
